travis:
  secure:
    BINSTAR_TOKEN: aqwExDi94JfY8WyDzwJjEfPMf2FFj8rU1IntgaJZSjepk7BhdPv8recsR1WQrytmeb+o/yfVX5DoVrbN+nxDLThBCX1tjVAb8ICAC7XwDEySFZECwiiGAOpOdIFuMB3rV/qmvYZxHXrGss0tXB3bN064vAjjxY1pBms6IRDcE21elAerQMVu/BWB6kofdOkAds9AZ3mugwhKzj4tQqmYhRUymETdoT/+dpN+B06h7VDiOk0dRF7KnXCGocUptHlD3j90NcppB1zupQ1a8yC2Zwbw8Q/1JzndTdBi45O5stY/jCqNVf2Ke3S1ouCDiYl4LuutASTjB2IDtLutwS8S4Zt0oadyBv4W9poV3/FdW8CBO0rE/f515AefiKv35d0nk1b0vZrx3FzIE3LsRlgcon/UeEpR8GhStZu9nZ+OLB/Q2C2VGj30IX9rlvkKsW9An8ciciQLSahH96IIHhcqDmxOFZmAojclfx6pC1Hto7dLCVvBhBQ7+EJHvsox145gO39cP/QTgA9MYfwyBJzfWj+rT8WoF7+fPlEMGLVJFPfaCWHKVoAbpoKsFMDw696a/hw3tHA0hF/GNLbTO4gUsTVeOKsYrHjhQSZi40OIPYAlnPc2tZvhobziPZA1UfpeNk52HTqnctzB6sdKux5wQv2DQmpG6LYQC2kreO0REto=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
